# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="<<YOUR_WIFI_NAME>>"
CIRCUITPY_WIFI_PASSWORD="<<YOUR_WIFI_PASSWORD>>"

# URL and credentials for your Nigthscout instace
NIGHTSCOUT_DOMAIN="<<YOUR_NIGHTSCOUT_BASE_DOMAIN>>"
NIGHTSCOUT_TOKEN="<<YOUR_NIGHTSCOUT_API_TOKEN>>"